# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letnik',
            fields=[
                ('letnik_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
