# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0002_delete_letnik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letnik',
            fields=[
                ('slug', models.SlugField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
