# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-08 08:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0005_auto_20170407_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
