# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-08 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_exam_exam_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_user',
        ),
    ]
