# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-08 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_remove_exam_exam_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_number',
            field=models.PositiveIntegerField(),
        ),
    ]
