# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-08 08:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_auto_20170408_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)]),
        ),
    ]
