# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-08 10:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0011_exam_exam_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
