# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-08 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0016_auto_20170408_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='exam_uploader',
            new_name='exam_user',
        ),
    ]
