# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-13 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0023_remove_exam_exam_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examfile',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='exams.Exam'),
        ),
    ]
