# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-15 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0024_auto_20170413_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examfile',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Exam'),
        ),
    ]
