# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0026_examcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examcomment',
            name='comment',
            field=models.CharField(max_length=255),
        ),
    ]
