# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-06 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0028_exam_needs_edit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='needs_edit',
        ),
    ]
