# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-06 19:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0029_remove_exam_needs_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
