# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-06 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0030_exam_exam_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='exam_likes',
            new_name='exam_mark',
        ),
    ]
