# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-19 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0031_auto_20170506_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
