# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-19 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0032_exam_exam_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_slug',
        ),
    ]
